// <auto-generated />
namespace DatabaseRelated.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FatherNameAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FatherNameAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202408130709237_Father Name Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
